server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/items/ {
        proxy_pass http://items-api:3000/items;
    }

    location /api/health {
        proxy_pass http://items-api:3000/health;
    }
}
